#!/usr/bin/perl

use v5.10;
use strict;
use warnings;

# Configuration
my $name = "berk";

my %colors = (
   'black'          => "[1;30m",
   'red'            => "[1;31m",
   'green'          => "[1;32m",
   'yellow'         => "[1;33m",
   'blue'           => "[1;34m",
   'magenta'        => "[1;35m",
   'cyan'           => "[1;36m",
   'white'          => "[1;37m",
   'light_black'    => "[30m",
   'light_red'      => "[31m",
   'light_green'    => "[32m",
   'light_yellow'   => "[33m",
   'light_blue'     => "[34m",
   'light_magenta'  => "[35m",
   'light_cyan'     => "[36m",
   'light_white'    => "[37m",
   'reset'          => "[1;0m"
);

my $timestamp = "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}";
my $url = "(((https?|ftp)|mailto):(//)?[^ <>\"[:blank:]]*|(www|ftp)[0-9]?\.[-a-z0-9.]+)";
my $nick = "<(.*?)>";
my $action = "ACTION (.*)?";
my $useless = "^-!- (.*)";

while (<>) {
   # Remove the huge timestamp from the line's beginning
   s/^$timestamp //;

   # Highlight nicknames, remove <> around them
   s/^$nick/$colors{'light_green'}$1$colors{'reset'} /;

   # Highlight me
   s/($name)/$colors{'light_red'}$1$colors{'reset'}/;

   # Highlight URLs
   s/$url/$colors{'light_blue'}$1$colors{'reset'}/;

   # Highlight /me actions
   s/$action/$colors{'magenta'}* $1 *$colors{'reset'}/;

   # Highlight "has joined", "changed mode", etc.
   s/^$useless/$colors{'black'}$1$colors{'reset'}/;

   print;
}
